version: '3.8'

networks:
  azure-function-development:
    driver: bridge

services:
  seed:
    build: ./Sample.App.Database
    environment:
      INCLUDE_TEST_DATA: 'Y'
    volumes:
      - ./Sample.App.Database/scripts:/app/scripts
      - ./Sample.App.Database/testData:/app/testData
      - ./Sample.App.Database/wait-for-it.sh:/app/wait-for-it.sh
    links:
      - db
    depends_on:
      - db
    working_dir: /app
    command:
      [
        './wait-for-it.sh',
        'db:1433',
        '--',
        'dotnet',
        './out/Sample.App.Database.dll',
        'Server=db,$DB_PORT;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASSWORD;',
      ]
    networks:
      - azure-function-development
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '$DB_PASSWORD'
    networks:
      - azure-function-development

  fun:
    build:
      context: .
      args:
        LOCAL: 'true'
    environment:
      AzureWebJobsStorage: 'UseDevelopmentStorage=true'
      FUNCTIONS_WORKER_RUNTIME: 'node'
      sqlServer: 'db'
      sqlPort: 1433
      sqlDatabase: '$DB_NAME'
      sqlUsername: '$DB_USER'
      sqlPassword: '$DB_PASSWORD'
    ports:
      - '7071:80'
    depends_on:
      - seed
      - db
    links:
      - db
    networks:
      - azure-function-development
