version: '3.8'
services:
  seed:
    build: .
    volumes:
      - ./scripts:/app/scripts
      - ./testData:/app/testData
      - ./wait-for-it.sh:/app/wait-for-it.sh
    links:
      - db
    depends_on:
      - db
    working_dir: /app
    environment:
      INCLUDE_TEST_DATA: 'Y'
    command:
      [
        './wait-for-it.sh',
        'db:1433',
        '--',
        'dotnet',
        './out/Sample.App.Database.dll',
        'Server=db,$DB_PORT;Database=$DB_NAME;User Id=$DB_USER;Password=$DB_PASSWORD;',
      ]

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '$DB_PORT:1433'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '$DB_PASSWORD'
