version: "3.8"
services:
  seed:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
    command:
      ["./wait-for-it.sh", "db:1433", "--", "dotnet", "run", "DropAndDatabase"]
    working_dir: /code
    environment:
      Sample_App_ConnectionString: "Server=db; Database=$DB_NAME; User id=$DB_USER; Password=$DB_PASSWORD"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "$DB_PORT:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "$DB_PASSWORD"
